### ISSUE TITLE
Sydney Morning Herald doesn't contain a lite version anymore

### ISSUE THREAD

**Issue by MewX** [mdibaiee/awesome-lite-websites#14]
see the link:
![image](https://user-images.githubusercontent.com/5752560/47895566-fde82b80-deb8-11e8-8177-13986bdf7da9.png)

heavy loads
![image](https://user-images.githubusercontent.com/5752560/47895479-7bf80280-deb8-11e8-81ef-05e0ce05cb33.png)

**Comment by MewX** [comment]
BTW, this is the last version you can view from the internet:

https://web.archive.org/web/20171228140028/http://www.smh.com.au/text/

Also, I recommend you to attach a `web archive` link for every website if you can't check them very frequently.

**Comment by mdibaiee** [comment]
@MewX ah, that's sad. If the lite version is gone I think the website doesn't really have a place in this list since it's not usable anymore. So whenever a website's lite version is gone, we should just delete it from the list. Thanks a lot for reporting this!
