### ISSUE TITLE
Some sites appear deprecated.

### ISSUE THREAD

**Issue by dannywarner** [mdibaiee/awesome-lite-websites#34]
Hello, 

Just came across the list and like the idea a lot. Looks like Skinny Guardian hasn't been updated since Dec 2020 and Text-Only News is just redirects to a hosting homepage now.

Just thought you might want to update those.

Thanks!

**Comment by mdibaiee** [comment]
@dannywarner thanks for the heads up. I will delete those two. You can always open PRs as well and I will review them! 👍
