### ISSUE TITLE
twitter mobile site no longer exists

### ISSUE THREAD

**Issue by dragontamer8740** [mdibaiee/awesome-lite-websites#46]
mobile.twitter.com redirects to the regular heavyweight twitter.

**Comment by lovelldies** [comment]
That's right. I'll make a PR to remove it.

**Comment by mdibaiee** [comment]
That's a shame, thanks for the PR

**Comment by celtic-coder** [comment]
Hi,

This may only be in the U.S. for the moment, because https://mobile.twitter.com/home is certainly working here in Ireland. The "mobile" URL is not [redirecting](https://wheregoes.com/trace/20225351326/) to another site.

Kind Regards,
Liam

**Comment by celtic-coder** [comment]
However, it was always a problem on desktop to get to the "mobile" site. So, this looks like the "mobile" URL sub-domain is now just a copy of the main domain. So, it looks like the "lite" site is no more. As mentioned above, this is a sad development.

**Comment by mdibaiee** [comment]
@celtic-coder that's what I noticed as well, mobile.twitter.com is not redirecting but is no different from the main website.
