### ISSUE TITLE
Afrika Radyo link dead

### ISSUE THREAD

**Issue by vlamacko** [mdibaiee/awesome-lite-websites#9]

**Comment by mdibaiee** [comment]
cc @azer do you have any information about this site? seems to be down, not sure if it's a temporary downtime or the service has been shut down

**Comment by azer** [comment]
@mdibaiee he-yo, it's a temporary downtime. I want to change the domain registrar, that's why I'm waiting :)

**Comment by mdibaiee** [comment]
@azer thanks for the info!

**Comment by mdibaiee** [comment]
@azer any updates on the matter?

**Comment by azer** [comment]
Hey, it's fixed now! thanks for the ping.
